// import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import styles from "./page.module.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={styles.layout}>
        <header>
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
}
